"""
Taboo card deck + deck helper. Pure data, no server concerns.

Each card: a guess word and five forbidden ("taboo") words the clue-giver
may not say.
"""

import random

# (GUESS WORD, taboo1, taboo2, taboo3, taboo4, taboo5)
_CARDS = [
    ("DOG", "Cat", "Puppy", "Bark", "Leash", "Pet"),
    ("VOLCANO", "Lava", "Erupt", "Mountain", "Ash", "Magma"),
    ("MONEY", "Cash", "Dollar", "Spend", "Bank", "Rich"),
    ("FAME", "Celebrity", "Star", "Famous", "Known", "Hollywood"),
    ("PIZZA", "Cheese", "Slice", "Italian", "Pepperoni", "Crust"),
    ("BEACH", "Sand", "Ocean", "Sun", "Waves", "Towel"),
    ("GUITAR", "Strings", "Strum", "Music", "Rock", "Band"),
    ("COFFEE", "Caffeine", "Morning", "Cup", "Beans", "Latte"),
    ("RAINBOW", "Colors", "Rain", "Sky", "Pot", "Gold"),
    ("SNOWMAN", "Frosty", "Carrot", "Winter", "Melt", "Build"),
    ("LIBRARY", "Books", "Quiet", "Read", "Shelf", "Borrow"),
    ("VAMPIRE", "Blood", "Fangs", "Dracula", "Bat", "Coffin"),
    ("BIRTHDAY", "Cake", "Candles", "Party", "Gift", "Age"),
    ("AIRPLANE", "Fly", "Pilot", "Wings", "Airport", "Sky"),
    ("DENTIST", "Teeth", "Drill", "Cavity", "Floss", "Chair"),
    ("UMBRELLA", "Rain", "Open", "Wet", "Handle", "Cover"),
    ("WEDDING", "Bride", "Groom", "Marriage", "Ring", "Vows"),
    ("GHOST", "Spooky", "Haunt", "Sheet", "Boo", "Scary"),
    ("SOCCER", "Ball", "Goal", "Kick", "Field", "Team"),
    ("HONEY", "Bee", "Sweet", "Sticky", "Bear", "Comb"),
    ("MIRROR", "Reflection", "Glass", "Look", "Face", "Bathroom"),
    ("PENGUIN", "Antarctica", "Bird", "Waddle", "Tuxedo", "Ice"),
    ("FIREWORKS", "Explode", "Sky", "July", "Loud", "Sparkle"),
    ("TOOTHBRUSH", "Teeth", "Paste", "Bathroom", "Bristles", "Clean"),
    ("ELEVATOR", "Floor", "Button", "Up", "Building", "Lift"),
    ("SUNGLASSES", "Eyes", "Sun", "Shade", "Cool", "Face"),
    ("VACUUM", "Carpet", "Dust", "Clean", "Suck", "Floor"),
    ("LADDER", "Climb", "Steps", "Rungs", "Tall", "Roof"),
    ("CAMERA", "Photo", "Picture", "Lens", "Snap", "Flash"),
    ("MERMAID", "Fish", "Tail", "Ocean", "Ariel", "Swim"),
    ("CACTUS", "Desert", "Spiky", "Plant", "Water", "Prickly"),
    ("KETCHUP", "Tomato", "Red", "Fries", "Bottle", "Mustard"),
    ("SCARECROW", "Field", "Crows", "Straw", "Corn", "Hat"),
    ("TORNADO", "Wind", "Spin", "Storm", "Funnel", "Kansas"),
    ("BUBBLE", "Pop", "Soap", "Blow", "Round", "Float"),
    ("MICROWAVE", "Heat", "Kitchen", "Popcorn", "Minute", "Beep"),
    ("SKELETON", "Bones", "Skull", "Body", "Halloween", "Ribs"),
    ("LIGHTHOUSE", "Light", "Ocean", "Ships", "Tower", "Beam"),
    ("TRAMPOLINE", "Jump", "Bounce", "Spring", "Backyard", "Flip"),
    ("HAMBURGER", "Bun", "Beef", "Patty", "Grill", "Fries"),
    ("ASTRONAUT", "Space", "Moon", "Rocket", "NASA", "Suit"),
    ("PIANO", "Keys", "Music", "Black", "White", "Play"),
    ("WATERMELON", "Fruit", "Seeds", "Green", "Summer", "Slice"),
    ("CHIMNEY", "Roof", "Smoke", "Santa", "Brick", "Fireplace"),
    ("NIGHTMARE", "Sleep", "Dream", "Scary", "Wake", "Bad"),
    ("SANDCASTLE", "Beach", "Bucket", "Sand", "Build", "Moat"),
    ("POPCORN", "Movie", "Butter", "Kernel", "Pop", "Bag"),
    ("EARTHQUAKE", "Shake", "Ground", "Tremor", "Fault", "Rumble"),
    ("SUBMARINE", "Underwater", "Navy", "Sonar", "Dive", "Yellow"),
    ("CATERPILLAR", "Butterfly", "Crawl", "Leaf", "Cocoon", "Green"),
    ("WATERFALL", "Water", "Cliff", "Fall", "River", "Niagara"),
    ("FLASHLIGHT", "Light", "Batteries", "Dark", "Beam", "Camping"),
    ("SNOWFLAKE", "Snow", "Winter", "Unique", "Cold", "Fall"),
    ("GRANDMOTHER", "Grandma", "Cookies", "Old", "Family", "Knit"),
    ("TREADMILL", "Run", "Gym", "Walk", "Belt", "Exercise"),
    ("PAINTBRUSH", "Paint", "Bristles", "Canvas", "Art", "Stroke"),
    ("HELICOPTER", "Fly", "Blades", "Rotor", "Hover", "Pilot"),
    ("PUMPKIN", "Orange", "Halloween", "Carve", "Pie", "Patch"),
    ("STETHOSCOPE", "Doctor", "Heartbeat", "Listen", "Chest", "Nurse"),
    ("SPIDERWEB", "Spider", "Sticky", "Silk", "Trap", "Corner"),
    ("KANGAROO", "Australia", "Hop", "Pouch", "Jump", "Joey"),
    ("TELESCOPE", "Stars", "Space", "Lens", "Look", "Astronomy"),
    ("LEMONADE", "Lemon", "Sour", "Stand", "Sugar", "Drink"),
    ("FIREPLACE", "Fire", "Wood", "Warm", "Mantle", "Chimney"),
    ("HALLOWEEN", "Costume", "Candy", "October", "Trick", "Pumpkin"),
    ("GRAVITY", "Fall", "Newton", "Down", "Force", "Apple"),
    ("IGLOO", "Ice", "Eskimo", "Snow", "Dome", "Cold"),
    ("PADLOCK", "Key", "Combination", "Lock", "Secure", "Chain"),
    ("SEATBELT", "Car", "Buckle", "Safety", "Click", "Strap"),
    ("CROSSWORD", "Puzzle", "Clues", "Words", "Grid", "Pencil"),
    ("TATTOO", "Ink", "Skin", "Needle", "Permanent", "Design"),
    ("HAMMOCK", "Hang", "Nap", "Trees", "Swing", "Relax"),
    ("WINDMILL", "Wind", "Blades", "Netherlands", "Spin", "Power"),
    ("FOSSIL", "Dinosaur", "Rock", "Ancient", "Bone", "Dig"),
    ("CONFETTI", "Party", "Throw", "Paper", "Celebrate", "Colorful"),
    ("STAPLER", "Paper", "Office", "Staples", "Click", "Bind"),
    ("GLACIER", "Ice", "Melt", "Slow", "Alaska", "Cold"),
    ("QUICKSAND", "Sink", "Sand", "Trap", "Struggle", "Jungle"),
    ("PARACHUTE", "Jump", "Sky", "Fall", "Plane", "Open"),
    ("WHIRLPOOL", "Water", "Spin", "Drain", "Vortex", "Suck"),
    ("MOUSETRAP", "Cheese", "Snap", "Catch", "Rodent", "Bait"),
    ("BAGPIPES", "Scotland", "Music", "Kilt", "Blow", "Instrument"),
    ("CHANDELIER", "Light", "Ceiling", "Crystal", "Fancy", "Hang"),
    ("SEAHORSE", "Ocean", "Fish", "Tail", "Tiny", "Curl"),
    ("DOORBELL", "Ring", "House", "Press", "Visitor", "Chime"),
    ("LULLABY", "Sleep", "Baby", "Song", "Sing", "Night"),
    ("TREEHOUSE", "Kids", "Branches", "Climb", "Backyard", "Build"),
    ("MOSQUITO", "Bite", "Buzz", "Blood", "Itch", "Bug"),
    ("AVOCADO", "Green", "Guacamole", "Pit", "Toast", "Fruit"),
    ("HIBERNATE", "Bear", "Winter", "Sleep", "Cave", "Months"),
    ("KARAOKE", "Sing", "Microphone", "Bar", "Song", "Lyrics"),
    ("PORCUPINE", "Quills", "Spikes", "Animal", "Sharp", "Rodent"),
    ("BOOMERANG", "Throw", "Return", "Australia", "Curve", "Wood"),
    ("HOPSCOTCH", "Chalk", "Jump", "Sidewalk", "Squares", "Kids"),
    ("YOGA", "Stretch", "Pose", "Mat", "Namaste", "Breathe"),
    ("FONDUE", "Cheese", "Dip", "Pot", "Chocolate", "Fork"),
    ("GONDOLA", "Venice", "Boat", "Canal", "Row", "Italy"),
    ("BLIZZARD", "Snow", "Storm", "Wind", "Cold", "Whiteout"),
    ("PINATA", "Candy", "Hit", "Stick", "Party", "Blindfold"),
    ("SUNFLOWER", "Yellow", "Tall", "Seeds", "Sun", "Petals"),
    ("WHISTLE", "Blow", "Referee", "Sound", "Loud", "Coach"),
    ("NAPKIN", "Wipe", "Table", "Mouth", "Paper", "Dinner"),
    ("COMPASS", "North", "Direction", "Needle", "Lost", "Map"),
    ("GARGOYLE", "Statue", "Stone", "Cathedral", "Ugly", "Roof"),
    ("TURTLE", "Shell", "Slow", "Reptile", "Ninja", "Pond"),
    ("SAXOPHONE", "Jazz", "Brass", "Reed", "Music", "Blow"),
    ("HANGOVER", "Alcohol", "Headache", "Morning", "Drink", "Regret"),
    ("LIGHTNING", "Thunder", "Storm", "Bolt", "Strike", "Flash"),
    ("ORIGAMI", "Paper", "Fold", "Japan", "Crane", "Art"),
    ("SPRINKLER", "Water", "Lawn", "Grass", "Spray", "Summer"),
    ("MUMMY", "Egypt", "Wrap", "Bandage", "Tomb", "Pharaoh"),
    ("CATAPULT", "Launch", "Medieval", "Castle", "Throw", "Rock"),
    ("PRETZEL", "Salt", "Twist", "Snack", "Dough", "Knot"),
    ("FLAMINGO", "Pink", "Bird", "Leg", "Lawn", "Florida"),
    ("ICEBERG", "Titanic", "Float", "Ocean", "Tip", "Cold"),
    ("SCRABBLE", "Tiles", "Letters", "Words", "Board", "Points"),
    ("JUKEBOX", "Music", "Coins", "Diner", "Songs", "Records"),
    ("MEATBALL", "Spaghetti", "Round", "Beef", "Sauce", "Sub"),
    ("TIGHTROPE", "Balance", "Circus", "Wire", "Walk", "Fall"),
    ("HEDGEHOG", "Spikes", "Sonic", "Curl", "Small", "Garden"),
    ("YO-YO", "String", "Spin", "Toy", "Trick", "Wind"),
    ("LASAGNA", "Pasta", "Layers", "Cheese", "Garfield", "Italian"),
    ("WHEELBARROW", "Garden", "Push", "Dirt", "Wheel", "Cart"),
    ("PELICAN", "Bird", "Beak", "Fish", "Pouch", "Coast"),
    ("QUARTERBACK", "Football", "Throw", "Team", "Pass", "NFL"),
    ("MOONWALK", "Jackson", "Dance", "Backward", "Slide", "Glide"),
    ("SEASHELL", "Beach", "Ocean", "Collect", "Sand", "Ear"),
    ("BROOMSTICK", "Sweep", "Witch", "Fly", "Bristles", "Clean"),
    ("CARTWHEEL", "Flip", "Gymnastics", "Hands", "Spin", "Grass"),
    ("DRAWBRIDGE", "Castle", "Moat", "Lower", "Chains", "Gate"),
    ("SNORKEL", "Swim", "Underwater", "Breathe", "Mask", "Tube"),
    ("THERMOMETER", "Temperature", "Fever", "Mercury", "Degrees", "Sick"),
    ("GRAFFITI", "Spray", "Wall", "Art", "Vandalism", "Paint"),
    ("WEREWOLF", "Moon", "Wolf", "Transform", "Howl", "Silver"),
    ("CUPCAKE", "Frosting", "Bake", "Small", "Cake", "Wrapper"),
    ("HULA HOOP", "Spin", "Waist", "Plastic", "Circle", "Hips"),
    ("BUTTERFLY", "Wings", "Caterpillar", "Flutter", "Net", "Cocoon"),
    ("PANCAKE", "Syrup", "Flip", "Breakfast", "Batter", "Stack"),
    ("DÉJÀ VU", "Before", "Feeling", "Repeat", "Memory", "Already"),
    ("ESCALATOR", "Stairs", "Moving", "Mall", "Step", "Up"),
    ("HOPSCOTCH", "Chalk", "Jump", "Sidewalk", "Squares", "Kids"),
    ("KOALA", "Australia", "Bear", "Eucalyptus", "Tree", "Cuddly"),
    ("MAGNET", "Metal", "Attract", "Fridge", "North", "Pull"),
    ("SANDPAPER", "Rough", "Wood", "Smooth", "Grit", "Sand"),
    ("TUXEDO", "Suit", "Formal", "Bowtie", "Wedding", "Black"),
    ("VOLLEYBALL", "Net", "Spike", "Beach", "Serve", "Ball"),
    ("XYLOPHONE", "Music", "Mallet", "Bars", "Bang", "Instrument"),
]

# de-dupe by guess word, keep first occurrence
_seen = set()
CARDS = []
for _c in _CARDS:
    if _c[0] not in _seen:
        _seen.add(_c[0])
        CARDS.append({"word": _c[0], "taboo": list(_c[1:])})


def shuffled_deck(rng=random):
    order = list(range(len(CARDS)))
    rng.shuffle(order)
    return order
